---
- name: Install httpd package
  yum:
    name: httpd
    state: present

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Add index.html to /var/www/html
  get_url:
    url: "{{ indexhtmlurl }}"
    dest: "{{ indexhtmldest }}"
    force: yes

- name: On your ansible server node create a new host (/etc/hosts) record with node1.opsschool.com pointing to node1 ip address
  lineinfile:
    path: /etc/hosts
    line: "{{ aliasrecord }}"
    create: yes

- name: Verify that server responds to http request and returns status 200
  uri:
    url: "{{ verifyurl }}"
    return_content: yes
  register: result
  until: '"{{ verifytext }}" in result.content'
